import numpy as np

CARD_FOR_PLAYING = 0
CARD_IN_HAND = 1
CARD_AVAILABLE = 2
CARD_CURR_TRICK_AGENT = 3
CARD_CURR_TRICK_OPPNT_1 = 4
CARD_CURR_TRICK_TEAM = 5
CARD_CURR_TRICK_OPPNT_2 = 6
CARD_PREV_TRICK_AGENT = 7
CARD_PREV_TRICK_OPPNT_1 = 8
CARD_PREV_TRICK_TEAM = 9
CARD_PREV_TRICK_OPPNT_2 = 10
CARD_TRUMP = 11


SUITS = ['S', 'H', 'C', 'D']
CARDS = ['2', '3', '4', '5', '6', '7', '8', '9', 'T', 'J', 'Q', 'K', 'A']
CARD_IDX = np.arange(len(CARDS)*len(SUITS)).reshape(CARDS, SUITS)

AGENT       = 0
OPPONENT_1  = 1
TEAMMATE    = 2
OPPONENT_2  = 3